name: payment-ci

on: 
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # full history for safe push later

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Use desired Node.js version

      - name: Install dependencies
        run: |
          cd src/payment
          npm ci

      # Test step removed

      # Lint step removed

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .               # changed from src/payment
          file: src/payment/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/payment-service:${{ github.run_id }}

  updatek8s:
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.TOKEN }}

      - name: Update tag in Kubernetes deployment manifest
        run: |
          sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/payment-service:${{ github.run_id }}|" kubernetes/payment/deploy.yaml
        shell: bash

      - name: Commit and push changes if any
        run: |
          git config --global user.email "vamsikadiyam444@gmail.com"
          gi

